version: "2.3"
services:
  gpu_job:
    build:
      dockerfile: ./nnsysident/Dockerfile
      context: ../
    image: nnsysident
    volumes:
      - .:/project
      - ../data_port:/src/data_port
      - /var/sinz-shared/mouse/toliaslab/static:/project/notebooks/data
    env_file: .env
    runtime: nvidia
    entrypoint: /usr/local/bin/python3
    command: run.py

  gpu_notebook:
    build:
      dockerfile: ./nnsysident/Dockerfile
      context: ../
    image: nnsysident
    volumes:
      - .:/project
      - ../data_port:/src/data_port
      - /var/sinz-shared/mouse/toliaslab/static:/project/notebooks/data
    env_file: .env
    runtime: nvidia